# Generated by Django 3.1.2 on 2020-10-11 05:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201009_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbpic',
            field=models.ImageField(default='controller_default.jpg', upload_to='gamethumbnails'),
        ),
        migrations.AddField(
            model_name='post',
            name='postdata',
            field=models.FileField(blank=True, upload_to=accounts.models.get_upload_path_files),
        ),
        migrations.AddField(
            model_name='post',
            name='postimage',
            field=models.ImageField(blank=True, upload_to=accounts.models.get_upload_path_images),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='', max_length=1),
        ),
    ]
