# Generated by Django 3.1.2 on 2020-10-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_game_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steamlink',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
