# Generated by Django 3.1.2 on 2020-10-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='gamerating',
            unique_together={('rated_for', 'rated_by')},
        ),
    ]
