# Generated by Django 3.1.2 on 2020-10-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201012_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
